version: '3.8'

volumes:
  datafiles:

services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_DATABASE=spoton
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - datafiles:/var/lib/mysql
      - ./db/spoton.sql:/docker-entrypoint-initdb.d/spoton.sql
    restart: always